global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  - "alert_rules.yml"

alerting:
  alertmanagers:
    - static_configs:
        - targets:
          - alertmanager_prod:9093

scrape_configs:
  # Analytics service metrics
  - job_name: 'analytics'
    static_configs:
      - targets: ['analytics_prod:8080']
    metrics_path: '/metrics'
    scrape_interval: 30s
    scrape_timeout: 10s

  # Prometheus self-monitoring
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  # Node exporter for system metrics
  - job_name: 'node'
    static_configs:
      - targets: ['node-exporter:9100']

  # PostgreSQL metrics
  - job_name: 'postgres'
    static_configs:
      - targets: ['postgres-exporter:9187']

  # Redis metrics
  - job_name: 'redis'
    static_configs:
      - targets: ['redis-exporter:9121']

  # Nginx metrics
  - job_name: 'nginx'
    static_configs:
      - targets: ['nginx-exporter:9113']

  # Application-specific metrics from web frontend
  - job_name: 'web-frontend'
    static_configs:
      - targets: ['web-app:3000']
    metrics_path: '/api/metrics'
    scrape_interval: 60s

  # Application-specific metrics from iOS app (via push gateway)
  - job_name: 'ios-app'
    static_configs:
      - targets: ['pushgateway:9091']
    honor_labels: true

# Remote write configuration for long-term storage
remote_write:
  - url: "http://thanos-receive:19291/api/v1/receive"
    queue_config:
      max_samples_per_send: 1000
      max_shards: 200
      capacity: 2500