global:
  smtp_smarthost: 'localhost:587'
  smtp_from: 'alerts@documentlearning.app'
  smtp_auth_username: 'alerts@documentlearning.app'
  smtp_auth_password: '${SMTP_PASSWORD}'

route:
  group_by: ['alertname', 'platform']
  group_wait: 10s
  group_interval: 10s
  repeat_interval: 1h
  receiver: 'web.hook'
  routes:
  - match:
      severity: critical
    receiver: 'critical-alerts'
  - match:
      severity: warning
    receiver: 'warning-alerts'

receivers:
- name: 'web.hook'
  webhook_configs:
  - url: 'http://analytics_prod:8080/api/alerts/webhook'
    send_resolved: true

- name: 'critical-alerts'
  email_configs:
  - to: 'admin@documentlearning.app'
    subject: 'CRITICAL: {{ .GroupLabels.alertname }} on {{ .GroupLabels.platform }}'
    body: |
      {{ range .Alerts }}
      Alert: {{ .Annotations.summary }}
      Description: {{ .Annotations.description }}
      Platform: {{ .Labels.platform }}
      Severity: {{ .Labels.severity }}
      Time: {{ .StartsAt }}
      {{ end }}
  slack_configs:
  - api_url: '${SLACK_WEBHOOK_URL}'
    channel: '#alerts-critical'
    title: 'Critical Alert: {{ .GroupLabels.alertname }}'
    text: |
      {{ range .Alerts }}
      *Platform:* {{ .Labels.platform }}
      *Alert:* {{ .Annotations.summary }}
      *Description:* {{ .Annotations.description }}
      *Time:* {{ .StartsAt }}
      {{ end }}

- name: 'warning-alerts'
  email_configs:
  - to: 'team@documentlearning.app'
    subject: 'WARNING: {{ .GroupLabels.alertname }} on {{ .GroupLabels.platform }}'
    body: |
      {{ range .Alerts }}
      Alert: {{ .Annotations.summary }}
      Description: {{ .Annotations.description }}
      Platform: {{ .Labels.platform }}
      Severity: {{ .Labels.severity }}
      Time: {{ .StartsAt }}
      {{ end }}
  slack_configs:
  - api_url: '${SLACK_WEBHOOK_URL}'
    channel: '#alerts-warning'
    title: 'Warning Alert: {{ .GroupLabels.alertname }}'
    text: |
      {{ range .Alerts }}
      *Platform:* {{ .Labels.platform }}
      *Alert:* {{ .Annotations.summary }}
      *Description:* {{ .Annotations.description }}
      *Time:* {{ .StartsAt }}
      {{ end }}

inhibit_rules:
  - source_match:
      severity: 'critical'
    target_match:
      severity: 'warning'
    equal: ['alertname', 'platform']