apiVersion: 1

datasources:
  - name: Prometheus
    type: prometheus
    access: proxy
    url: http://prometheus:9090
    isDefault: true
    editable: true

  - name: Loki
    type: loki
    access: proxy
    url: http://loki:3100
    editable: true

  - name: Analytics DB
    type: postgres
    access: proxy
    url: analytics_db:5432
    database: analytics
    user: analytics
    secureJsonData:
      password: password
    jsonData:
      sslmode: disable
    editable: true